### ISSUE TITLE
Can you please make this work in Android O? 

### ISSUE THREAD

**Issue by srujanb** [BaselHorany/ProgressStatusBar#2]
This library looks good. I wish I could try in Android O. Can this anyhow be implemented on and onwards O?

**Comment by BaselHorany** [comment]
Sorry Google don't Allow this anymore, many famous apps are infected. I can do nothing about it.

**Comment by AndroidDeveloperLB** [comment]
Can't you put the progress behind or something?

**Comment by BaselHorany** [comment]
If you like to, you can convert it to be a part of a layout for a fullscreen activity with a translucent statusbar.
this is not practical to a library.

**Comment by AndroidDeveloperLB** [comment]
Can you put a sample for it nevertheless? It just looks nice...

**Comment by BaselHorany** [comment]
I don't have enough time these days but I will do it later.

**Comment by srujanb** [comment]
I guess this is not impossible. Facebook messenger does show certain information in statusbar and it works on my Android O. Looks like they just have new APIs.

**Comment by AndroidDeveloperLB** [comment]
Can you please try something, then?

**Comment by srujanb** [comment]
HAHA! I only wish. I have three projects ongoing at the same time. I might plan to do it in summer but before that, no chance. Apologize.

**Comment by BaselHorany** [comment]
That is interesting. However, I haven't tried it yet, have you?

**Comment by AndroidDeveloperLB** [comment]
Which projects, if I may ask?

**Comment by srujanb** [comment]
Not yet

**Comment by BaselHorany** [comment]
I hope you test it when possible

**Comment by srujanb** [comment]
Here is what I'm talking about
Check the statuabar

![](https://i.imgur.com/U1YHIaE.jpg)

**Comment by BaselHorany** [comment]
Yes I got this, I meant to test the library

**Comment by srujanb** [comment]
Got that. Just wanted to show what I meant.

**Comment by BaselHorany** [comment]
Aha now I figured out that Facebook is a considered as a system level app in recent android versions "it comes previously installed and can't be deleted" thus it can do what other apps can't.
as you can read here 
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#TYPE_SYSTEM_OVERLAY

> This constant was deprecated in API level 26. for non-system apps

**Comment by srujanb** [comment]
Well, you're mistaken again. First of all this screenshot is a part of Messenger app not Facebook app. Anyways, neither Facebook nor Messenger were a part of my device when I bought. I installed them later on. I can uninstall either of the apps any day.

**Comment by BaselHorany** [comment]
there is no other way to smoothly add views above status bar

**Comment by AndroidDeveloperLB** [comment]
What about below it, that will get merge as it could be transparent (or semi transparent)  ?
Is that possible?

**Comment by BaselHorany** [comment]
now in v1.1.5 Oreo and above are supported.

**Comment by AndroidDeveloperLB** [comment]
@BaselHorany  Can you please share a screenshot/animation of how it looks now there?

**Comment by BaselHorany** [comment]
It is the same except that statusbar remains visible, as you suggested, below it.

**Comment by AndroidDeveloperLB** [comment]
@BaselHorany Please show, nevertheless. Maybe even put it on the main page of the repository, so that people would understand the difference of how it looks on all the versions of the OS

**Comment by BaselHorany** [comment]
right that is better, I added a clarification with other new changes

**Comment by AndroidDeveloperLB** [comment]
Seems nice. Thanks.

**Comment by BaselHorany** [comment]
thank you
